spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      idle-timeout: 1800000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: datahiraka
      connection-test-query: SELECT 1
  redis:
    database: 3
    lettuce:
      pool:
        max-idle: 200
        max-active: 8
        max-wait: 10000ms
  rabbitmq:
    port: 5672
    stream:
      username: guest
      password: guest
  profiles:
    active: prod
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.example.demo.pojo

logging:
  level:
    com.example.demo.mapper: debug


